### ISSUE TITLE
Is there any resource on market basket analysis?

### ISSUE THREAD

**Issue by AmitHasanShuvo** [eugeneyan/applied-ml#145]
There's no doubt this is one of the best resources on applied ML. Market basket analysis is one of the key things in business. But using association rules on the datasets fails due to huge frequent itemset generations. Are there any resource here or your suggestions on it?

**Comment by chauhankaranraj** [comment]
Hey @AmitHasanShuvo, at Red Hat our team was looking into a problem which I think was fairly similar to a market basket analysis. Basically, we were trying to understand which kubernetes issues tend to co-occur frequently (i.e. frequent pattern and association rule mining applied to k8s clusters' health data).

For this, our initial approach was to perform clustering + fpgrowth on the "symptoms" seen in problematic clusters, and then prune the resulting itemsets using some heuristics. Based on the outputs of this approach, we were able to write "rules" to concretely define some failure modes in k8s clusters. Feel free to read about it [here](https://www.operate-first.cloud/data-science/openshift-anomaly-detection/docs/blog/diagnosis-discovery-blog.md) or watch the [talk](https://www.youtube.com/watch?v=RPBXma8NY0s).

disclaimer: I am not a contributor to this repo (not yet, at least :)) or affiliated with it in any other way

**Comment by AmitHasanShuvo** [comment]
I really appreciated your response. Thanks a lot.
