### ISSUE TITLE
Duplicated resource

### ISSUE THREAD

**Issue by almeida-caio** [eugeneyan/applied-ml#177]
Hi (:
First of all, thank you so much for gathering all this intel.

Just opening a very simple issue: on the [Data Discovery](https://github.com/eugeneyan/applied-ml#data-discovery) section of the README file, there are two identical resources, cf. items 10 & 18 on the rendered blob. The only difference is that one of them also includes a link to the corresponding repo.

Here's a screenshot, showing that the URLs are the same:
![duplicate](https://user-images.githubusercontent.com/78153441/135339358-c98470c4-81a9-4557-89f3-5f84edd1e51a.png)

**Comment by eugeneyan** [comment]
Thanks for catching this! Fixed!
